### ISSUE TITLE
0.5.0 not installable from pypi package

### ISSUE THREAD

**Issue by mgorny** [readthedocs/sphinx_rtd_theme#946] opened 2020-06-18 07:54 UTC
### Problem

The new 0.5.0 cannot be built from pypi sdist tarballs due to the new webpack building logic. If I'm not mistaken, the prerequisite files are missing from the tarball. Furthermore, I dare say it'd be really preferable if sdist included the prebuilt webpack and building it yourself would be only necessary when using git checkout.

### Reproducible Project

```sh
wget https://files.pythonhosted.org/packages/59/cd/1eb84d8b11ecac97a85c42199bb5566eee0bb946b27138f28cbea1d729e7/sphinx_rtd_theme-0.5.0.tar.gz
tar -xf sphinx_rtd_theme-0.5.0.tar.gz 
cd sphinx_rtd_theme-0.5.0
python setup.py build
```

#### Error Logs/Results

```
running build
running build_py

> sphinx_rtd_theme@0.5.0 preinstall /tmp/sphinx_rtd_theme-0.5.0
> bin/preinstall.js

sh: bin/preinstall.js: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sphinx_rtd_theme@0.5.0 preinstall: `bin/preinstall.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sphinx_rtd_theme@0.5.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mgorny/.npm/_logs/2020-06-18T07_52_09_537Z-debug.log
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 22, in run
    subprocess.run(['npm', 'install'], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
```

#### Expected Results

It should build successfully ;-).

### Environment Info

- Python Version: 3.8.3
- Sphinx Version: 3.1.1
- RTD Theme Version: 0.5.0

**Comment by agjohnson** [comment] 2020-06-18 23:47
Ah thanks for the report, we didn't test source dist building. There are a few extra files to include it looks like.

I don't think we'll back out of requiring building when working with source files. We're hoping to eventually require this even for usage from GitHub -- no built binaries will be included in the Git repo at all. Obviously we need to tune the distribution files a bit more though.

I'll target next release with a fix.

**Comment by stsewd** [comment] 2020-10-07 22:45
Looks like a duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/946

**Comment by mgorny** [comment] 2020-10-08 03:07
> Looks like a duplicate of #946

Are you sure you meant to say it on this bug?

**Comment by stsewd** [comment] 2020-10-08 03:20
sorry, this issue is https://github.com/readthedocs/sphinx_rtd_theme/issues/990

**Comment by adamjstewart** [comment] 2020-10-15 15:21
Since #990 was closed this can also probably be closed

**Comment by stsewd** [comment] 2020-10-15 15:24
We still need to release a new version, but this is fixed, yeah

**Closed by stsewd** 2020-10-15 15:24 UTC
Labels: Accepted, Bug
