### ISSUE TITLE
nav menu structure

### ISSUE THREAD

**Issue by AM-77** [readthedocs/sphinx_rtd_theme#763] opened 2019-05-23 18:04 UTC
### Problem
nav structure incompatible with the folder structure.

#### Expected Results
the service folder and the service.md should be in the same level

![Screenshot_2019-05-23 Services - Nyno 🌕(1)](https://user-images.githubusercontent.com/18232579/58275510-7bac4f80-7d95-11e9-9813-4941d17b4c87.png)

![Screenshot from 2019-05-23 19-53-44](https://user-images.githubusercontent.com/18232579/58275606-be6e2780-7d95-11e9-84fb-644ead163cca.png)

also incorrect links
![Screenshot from 2019-05-23 19-55-25](https://user-images.githubusercontent.com/18232579/58275614-c29a4500-7d95-11e9-81d9-29fe35d33771.png)

**Comment by jessetan** [comment] 2019-06-26 18:08
Can you provide example code to reproduce this? This looks like section headers use an incorrect underline.

**Comment by agjohnson** [comment] 2019-10-18 18:21
Closing. No more information provided.

**Closed by agjohnson** 2019-10-18 18:21 UTC
Labels: Needed: more information
