### ISSUE TITLE
Break text inside wide tables

### ISSUE THREAD

**Issue by AstroMatt** [readthedocs/sphinx_rtd_theme#716] opened 2019-01-17 22:46 UTC
### Problem

There's a problem with displaying long text inside tables and code listings.
Half of the screen is not used (which is annoying on widescreen 4K monitors).
Can you at least provide break text instead of requiring horizontal scrolling?
I tried to break text manually by `\n` `<br>` etc, but I wasn't able to do so.

### Reproducible Project

http://python.astrotech.io/date-and-time/parse-and-format.html#table-of-date-and-time-parsing-and-formatting-parameters

### Environment Info

- Python Version: 3.7.2
- Sphinx Version: 1.8.3
- RTD Theme Version: 0.4.2

**Comment by myii** [comment] 2019-03-01 15:05
@AstroMatt The CSS workarounds in #117 will probably be useful to you.

**Comment by stsewd** [comment] 2020-10-08 20:31
Closing this as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/117

**Closed by stsewd** 2020-10-08 20:31 UTC
