### ISSUE TITLE
Tables need not be scrolling

### ISSUE THREAD

**Issue by danielquinn** [readthedocs/sphinx_rtd_theme#259] opened 2015-11-02 15:42 UTC
After searching through the issue queue, I see that the current wisdom on forcing `nowrap` on all table data cells is that it looks terrible on mobile, which I concede, but on a mouse-driven interface, this nowrap rule renders the content basically unreadable.

The good news though is that it need not be this way and that we can have both environments be reader-friendly, just use `@media`:

``` css
@media screen and (max-width: 767px) {
    .wy-table-responsive table td {
        white-space: nowrap;
    }
}
```

I'm not familiar with SASS, but there must be a way to implement these sorts of rules with it, yes?  This would make `td` cells scrollable on small devices, and readable on larger ones.  I don't see the downside.

**Comment by uralbash** [comment] 2016-01-20 09:39
+1

**Comment by reneme** [comment] 2016-02-10 10:32
+1

**Comment by benjaoming** [comment] 2017-06-15 20:12
There's a nice work-around guide here: http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

**Comment by benjaoming** [comment] 2017-06-15 20:14
This seems to be a duple of #117

**Comment by stsewd** [comment] 2020-10-08 22:06
Thanks for pointing that out. Closing as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/117

**Closed by stsewd** 2020-10-08 22:06 UTC
