### ISSUE TITLE
Citation is different in Sphinx > 2.0

### ISSUE THREAD

**Issue by williamjamir** [readthedocs/sphinx_rtd_theme#814] opened 2019-08-28 15:53 UTC
Using the same `.rst ` from the Demo available here: [Link for the reference demo example](https://github.com/readthedocs/sphinx_rtd_theme/blob/a3ab477aaa23f3b7ab7d62c7abc2cc74102ab2b8/docs/demo/demo.rst#citations)

### Sphinx 1.8.5
- Os: Win64
- Python Version: 3.6.7
- Sphinx Version: 1.8.5
- RTD Theme Version: 0.4.3

![image](https://user-images.githubusercontent.com/5083518/63871484-5cbfe980-c992-11e9-9478-145d0a74c873.png)

### Sphinx 2.2.0 (and 2.0.1 as well)
- Os: Win64
- Python Version: 3.6.7
- Sphinx Version: 2.2.0
- RTD Theme Version: 0.4.3

![image](https://user-images.githubusercontent.com/5083518/63871598-89740100-c992-11e9-982d-089f5a54e178.png)

**Comment by agjohnson** [comment] 2019-10-18 17:50
Likely a duplicate of #800. That one will be addressed first, and hopefully clears up this issue as well.

**Comment by agjohnson** [comment] 2019-10-19 02:49
Closing. Direct duplicate of #741

**Closed by agjohnson** 2019-10-19 02:49 UTC
Labels: Accepted, Bug
