### ISSUE TITLE
Inconsistent spaces in C++ function definitions with links

### ISSUE THREAD

**Issue by ZedThree** [readthedocs/sphinx_rtd_theme#647] opened 2018-05-29 14:42 UTC
### Problem

There is some missing whitespace in function definitions that contain links, at least in the `cpp` domain. Consider the following restructuredtext documenting some C++ type and function:

```rst
.. default-domain:: cpp

.. cpp:type:: MyType

   Some type

.. cpp:function:: const MyType Foo(const MyType bar)

   Some function type thing
```

I get the following:
![bad_rtd_theme](https://user-images.githubusercontent.com/1486942/40665305-ce60ebfc-6354-11e8-9cdb-0c75b682e680.png)

with spaces missing after `MyType`.

#### Expected Results

Something like this:
![good_rtd_theme](https://user-images.githubusercontent.com/1486942/40665697-d788732a-6355-11e8-9884-2afcfb521188.png)
Note the spaces around `MyType` link in the definition of `Foo`.

I did this by changing the following with the Inspect tool in Chrome:

```diff
  .rst-content dl:not(.docutils) dt {
-      display: table;
+      display: table-cell;
   ...
```

which I think comes from [here](https://github.com/rtfd/sphinx_rtd_theme/blob/34cc4a2aeca44d1204de135e4d68700077f595a2/sass/_theme_rst.sass#L316)

Note that now there is extra padding to the right of `const`, but not `type`, which I couldn't fix just by deleting `padding-right: 8px;` on `.rst-content dl:not(.docutils) .property`

### Environment Info

- Python Version: 3.6.5
- Sphinx Version: 1.7.5
- RTD Theme Version: 0.3.1

Also with the defaults on rtd

**Comment by binaryzebra** [comment] 2019-01-25 20:46
<img width="583" alt="2019-01-25 23 46 15" src="https://user-images.githubusercontent.com/882216/51771871-7ac32400-20fb-11e9-87fc-1d8da2e687d0.png">
<img width="606" alt="2019-01-25 23 46 07" src="https://user-images.githubusercontent.com/882216/51771872-7ac32400-20fb-11e9-8bd6-819fd0124002.png">

Same problem.

**Comment by lgritz** [comment] 2019-05-30 20:33
I'm experiencing this, too. Is anybody working on a fix?

**Comment by agjohnson** [comment] 2019-07-25 19:29
@lgritz there are currently no PRs addressing this issue, no

**Comment by stsewd** [comment] 2020-10-08 21:06
Closing as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/694

**Closed by stsewd** 2020-10-08 21:06 UTC
