### ISSUE TITLE
navigation_depth, collapsing, and local vs remote builds

### ISSUE THREAD

**Issue by svenevs** [readthedocs/sphinx_rtd_theme#457] opened 2017-09-04 23:23 UTC
Hello.  I'm getting a little turned around on how to use the `html_theme_options` with your (beautiful!) theme.  To be clear, I'm actually only interested in `navigation_depth` displaying remotely, I'm including the collapse stuff because other issues on here seem to indicate an interplay between the two that may be relevant.  Local testing does **not** seem to indicate that `collapse_navigation` has an effect on this issue, it is included for completeness.

### Relevant section of `conf.py`

```py
import os
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_theme_options = {
    "navigation_depth": 5,
    "collapse_navigation": False
}
```

### Local results seem jumbled

When building the site locally, `navigation_depth` seems to get the wrong parent relationships.  For reference, every `toctree` directive has a `:maxdepth:` of `5` for consistency here, but the same is observed with `4`, etc.  The presented output has the sub-sub sections displayed out-idented in the sidebar.

![parenting](https://user-images.githubusercontent.com/5871461/30039849-7f0df27a-918b-11e7-880e-c9373121b7da.jpeg)

The view from the other "module" being documented in the project:

![parenting_2](https://user-images.githubusercontent.com/5871461/30039864-ae84a0d0-918b-11e7-840c-f9c96a4e657e.jpeg)

The code is all available here: https://github.com/svenevs/sphinx-rtd-tocdepth-confusion-demonstration

### Remote builds don't use `navigation_depth`?

I made a quick RTFD site, the only difference between the two builds is the `master` branch uses the default `"collapse_navigation"`, and the `collapse_false` branch uses `"collapse_navigation": False`.  Neither seem to be using the theme options though.

- [`master` docs build](http://sphinx-rtd-tocdepth-confusion-demonstration.readthedocs.io/en/latest/index.html)
- [`collapse_false` docs build](http://sphinx-rtd-tocdepth-confusion-demonstration.readthedocs.io/en/collapse_false/)

For reference, the versions of both Sphinx and this theme on the local and remote hosts are the same (latest stable from fresh installs, checked with some printouts on RTD).

### In the end

I imagine this would be difficult to track down, and definitely don't expect anything to come of it.  I greatly appreciate the theme, and wanted to provide a detailed account of what seems to be a bug :wink:

**Comment by Blendify** [comment] 2017-12-16 21:59
Can you try using the master branch on RTD and locally? There have been a couple fixes here recently.

**Comment by Blendify** [comment] 2018-04-18 02:16
No reply, closing.

**Comment by svenevs** [comment] 2018-04-18 10:03
Hi @Blendify,

Sorry for missing the first e-mail about this.  I tried with the latest master both locally and on RTD and get [the same results](http://sphinx-rtd-tocdepth-confusion-demonstration.readthedocs.io/en/latest/reference_someModule.html).

Please forgive my ignorance, I could not figure out how to copy-paste from the inspector.  It appears that the childhood relationships as far as the `<ul>` and `<li>` are correct.  It's just that the styling seems to place the `toctree-l5` in the wrong location.

![sphinx_rtd_theme](https://user-images.githubusercontent.com/5871461/38925593-f27a9af8-42b4-11e8-9647-1044a8a9f398.jpeg)

**Comment by svenevs** [comment] 2018-04-18 11:49
Ok I think I found it!

https://github.com/rtfd/sphinx_rtd_theme/blob/7cd846b4fdd0e971f2c409ad9a2af24070b7b111/sass/_theme_layout.sass#L100

and

https://github.com/rtfd/sphinx_rtd_theme/blob/7cd846b4fdd0e971f2c409ad9a2af24070b7b111/sass/_theme_layout.sass#L132-L133

I think just a `li.toctree-l5` part is needed here?  As far as I understand, `:maxdepth: 5` for toctrees is all that Sphinx expects people to support (I think that actually comes from `docutils` but I'm not entirely sure).  I gave a vain attempt at changing things, but (as evidenced by above) I know very little about HTML / CSS / SASS and how to test it.  I am happy to test locally with a patch or from a branch or fork, but don't know how to make the changes myself :/

**Comment by svenevs** [comment] 2018-04-19 20:38
Some more information.

- `sphinx` and `rst2html.py` will (as far as I understand) generate up to 31 (?) header levels.

    ```py
    #!/usr/bin/env python
    
    import textwrap
    
    # from: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections
    all_markers = '! " # $ % & ' + "' " +  '( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~'
    markers = all_markers.split(" ")
    
    with open("index.rst", "w") as index:
        for idx in range(len(markers)):
            index.write(textwrap.dedent('''
                Section {0}
                {1}
    
                Some text for section {0}.
    
            '''.format(
                idx, markers[idx] * 80
            )))
    ```

    This will generate an `index.rst`.  After generated, you can use that as an `index.rst` in some sphinx project, or run `rst2html.py index.rst > index.html`.  I think I may have found a sphinx bug related to this, but it shouldn't be a problem as far as this theme is concerned.
- (I believe) for `html` (in general), the farthest this should need to go in terms of browser support is `<h6>`.  Meaning styling should be updated to add
    1. `li.toctree-l5` support
    2. `li.toctree-l6` support

**Comment by huataihuang** [comment] 2019-06-16 10:14
I use sphinx-rtd-theme-0.4.3 , lastest version. When set conf.py 

```
html_theme_options = {
    'navigation_depth': 5
}
```

Sidebar seems to miss-behave. Topics will not properly indent relative to parent topics.

**Comment by jessetan** [comment] 2019-06-26 17:07
The theme only handles navigation-depth up to 4 well, see #540. This needs a design decision and some code changes to make it work

**Comment by agjohnson** [comment] 2019-07-25 21:03
Closing this as a duplicate of #540. Feel free to follow along there.

**Closed by agjohnson** 2019-07-25 21:03 UTC
Labels: Design, Needed: design decision
