### ISSUE TITLE
Search does not terminate for terms that are not found. 

### ISSUE THREAD

**Issue by noraabiakar** [readthedocs/sphinx_rtd_theme#1037] opened 2021-01-18 10:41 UTC
### Problem

Searching for a string in the docs using the search bar does not terminate ( result is stuck on `Searching ...` ) when the string is not found.

### Reproducible Project

This can be reproduced on: https://sphinx-rtd-theme.readthedocs.io/en/latest/ by searching some random string that isn't present. 
But has also been observed on: https://arbor.readthedocs.io/en/latest/ which uses this theme.

#### Expected Results:

This message to be displayed instead (or something similar): 
`Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.`

### Environment Info

- Python Version: Python3.7
- Sphinx Version: v3.4.3
- RTD Theme Version: v0.5.1 (as well as master)

**Comment by stsewd** [comment] 2021-01-18 18:07
This seems related to the sphinx change https://github.com/readthedocs/sphinx_rtd_theme/pull/1021, maybe something with our extension and not with the theme.

**Comment by stsewd** [comment] 2021-01-18 19:14
I think I know were the problem is, this is because we install by default an old version of the theme, you should pin your version to `0.5.1` (this is fixed there). For our docs we need to install it with pip

**Comment by Blendify** [comment] 2021-03-11 21:00
This was fixed with 24f8e31c5b77131a25e6ed99533a4bbca969b2f0, note the theme currently is using an old version of the theme so that's why our search is bugged

**Closed by Blendify** 2021-03-11 21:00 UTC
Labels: Bug
