### ISSUE TITLE
Missing fonts/RobotoSlab/roboto-slab.eot cause error for django collectstatic

### ISSUE THREAD

**Issue by kwinata** [readthedocs/sphinx_rtd_theme#825] opened 2019-10-08 05:07 UTC
### Problem

When I do `make html`, and open the `index.html` locally or even host it as static file, it works fine. But when I use django collectstatic to host the static pages using django, I got an error as shown in the section below.

I think there is no issue in opening it as static page because it will fallback the font to the `fonts/RobotoSlab/roboto-slab-v7-regular.eot`. So my current patch is just to copy the file after the `make html`.
``` Makefile
docs:
	@make html
	@cp $(BUILDDIR)/html/_static/fonts/RobotoSlab/roboto-slab-v7-regular.eot $(BUILDDIR)/html/_static/fonts/RobotoSlab/roboto-slab.eot
```

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.
```
Post-processed 'silk/lib/highlight/foundation.css' as 'silk/lib/highlight/foundation.c93165b50e87.css'
Post-processing '_static/css/theme.css' failed!

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
    raise processed
whitenoise.storage.MissingFileError: The file '_static/fonts/RobotoSlab/roboto-slab.eot' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x10c1ebcc0>.

The CSS file '_static/css/theme.css' references a file which could not be found:
  _static/fonts/RobotoSlab/roboto-slab.eot

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

### Environment Info

- Python Version: 3.7
- Sphinx Version: 2.2.0
- RTD Theme Version: 0.4.3

**Comment by agjohnson** [comment] 2019-10-15 21:35
This looks like a rather custom thing and I don't know if this would even be an issue with the theme. I'm going to close this issue, but if you find a fix for an issue with the theme, feel free to report or reopen this issue.

**Closed by agjohnson** 2019-10-15 21:35 UTC

**Comment by kleptog** [comment] 2019-11-06 12:41
For other people running into this problem, I found the cause. Namely, theme.css references url("../fonts/RobotoSlab/roboto-slab.eot") but this file is not actually supplied by the theme.

At least, not in sphinx-rtd-theme 0.4.3. In the current master this has all been changed. But it seems to apply to all 0.4.x releases. I suppose it's uncommon to process sphinx themes with Django collectstatic.

As such, I don't think closing this issue was appropriate, but it's probably fixed in the next release.

**Comment by pallavg** [comment] 2020-03-03 19:33
I also faced the same problem with 0.4.3 and had to downgrade. It would be a good if a new release could be made. Thanks.
