### ISSUE TITLE
[UI improvement] - Enable Dark theme toggle

### ISSUE THREAD

**Issue by swastkk** [readthedocs/sphinx_rtd_theme#1440] opened 2023-02-19 18:17 UTC
It's the best theme for the documentation, but if we can include the dark theme in it too like having a toggle button for the theme change.
Signed-off-by- swastik <swastkk@gmail.com>

**Comment by benjaoming** [comment] 2023-02-20 08:48
Thanks for taking the time to open an issue. It is - however - a duplicate of this issue: https://github.com/readthedocs/sphinx_rtd_theme/issues/224

So I'm going to close this one.

**Closed by benjaoming** 2023-02-20 08:48 UTC
