### ISSUE TITLE
Weird numpydoc-generated parameter tables after upgrade to v0.5.0

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/sphinx_rtd_theme#949] opened 2020-06-22 07:05 UTC
### Problem

I use `napoleon` and `autosummary` for numpydoc-style automatic documentation generation. All the pages in my "API Reference" section switched from the "Expected Result" to the "Actual Result" after upgrading to version 0.5.0 (see below).

For details, you can also compare [this older version](https://proplot.readthedocs.io/en/v0.6.4/api.html) of my docs on readthedocs.io, generated with `sphinx_rtd_theme` 0.4.3, with the [stable version](https://proplot.readthedocs.io/en/stable/api.html), generated with 0.5.0. Note the results are the same when I generate the documentation locally.

#### Expected Result

Normal numpydoc-style parameter tables:

<img width="730" alt="Screen Shot 2020-06-22 at 12 03 42 AM" src="https://user-images.githubusercontent.com/19657652/85253632-d8a48a00-b41b-11ea-841d-1c403fcf02f4.png">

#### Actual Result

Weird tables, with parameter lists bleeding into the margin and a two-column table rather than bullet points for parameter names:

<img width="1013" alt="Screen Shot 2020-06-22 at 12 02 36 AM" src="https://user-images.githubusercontent.com/19657652/85253553-b01c9000-b41b-11ea-9bd6-33e44e019e92.png">

### Reproducible Project

Documentation tree: https://github.com/lukelbd/proplot/tree/master/docs

Relevant contents of `conf.py`:

```python
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'IPython.sphinxext.ipython_console_highlighting',
    'IPython.sphinxext.ipython_directive',  # for ipython highlighting
    'sphinx.ext.autodoc',  # include documentation from docstrings
    'sphinx.ext.doctest',  # >>> examples
    'sphinx.ext.extlinks',  # for :pr:, :issue:, :commit:
    'sphinx.ext.autosectionlabel',  # use :ref:`Heading` for any heading
    'sphinx.ext.todo',  # Todo headers and todo:: directives
    'sphinx.ext.mathjax',  # LaTeX style math
    'sphinx.ext.viewcode',  # view code links
    'sphinx.ext.napoleon',  # for NumPy style docstrings
    'sphinx.ext.intersphinx',  # external links
    'sphinx.ext.autosummary',  # autosummary directive
    'sphinxext.custom_roles',  # local extension
    'sphinx_copybutton',
    'sphinx_automodapi.automodapi',  # see: https://github.com/lukelbd/sphinx-automodapi/tree/proplot-mods # noqa
    'nbsphinx',
]

# Napoleon options
# See: http://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
napoleon_use_ivar = False
napoleon_use_param = False
napoleon_use_keyword = False
napoleon_use_rtype = False
napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_include_init_with_doc = False  # move init doc to 'class' doc

# Rtd theme
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'logo_only': True,
    'display_version': False,
    'collapse_navigation': True,
    'navigation_depth': 4,
    'prev_next_buttons_location': 'bottom',  # top and bottom
}
```

### Environment Info

- Python Version: 3.6
- Sphinx Version: 3.1.1
- RTD Theme Version: 0.5.0

**Comment by agjohnson** [comment] 2020-06-22 16:22
@lukelbd Thanks for the report. This might be a theme bug, however I haven't seen this replicated in any of other autodoc usage. I see you're doing something custom on your docs, using an extension[1] to generate the autodoc output. Could you verify that this is not the source of the problem first?

1: https://github.com/lukelbd/proplot/blame/master/docs/api.rst#L10

**Comment by lukelbd** [comment] 2020-06-22 16:28
> I see you're doing something custom on your docs, using an extension[1] to generate the autodoc output. Could you verify that this is not the source of the problem first?

Sure I'll check when I get the chance. I guess [sphinx-automodapi](https://github.com/astropy/sphinx-automodapi) could be incompatible with v0.5

**Comment by lukelbd** [comment] 2020-06-23 22:55
Created a minimal branch without any custom templates or style overrides, and without the `sphinx-automodapi` plugin -- results are the same. The issue seems to be that the headers/parameters are put in 2 separate columns:

<img width="1318" alt="Screen Shot 2020-06-23 at 4 40 51 PM" src="https://user-images.githubusercontent.com/19657652/85473331-4feb3280-b570-11ea-9978-99a7caf0066b.png">

This causes margin bleed only when there is a too-wide table in the parameters section (in version 0.4.3, you can horizontally scroll this table):

<img width="1013" alt="Screen Shot 2020-06-23 at 4 41 32 PM" src="https://user-images.githubusercontent.com/19657652/85473400-685b4d00-b570-11ea-818a-a27544e3daf6.png">

But it still looks cramped even without the margin bleed (those Parameters/Other Parameters should be section headers). Version 0.5.0:

<img width="753" alt="Screen Shot 2020-06-23 at 4 43 35 PM" src="https://user-images.githubusercontent.com/19657652/85473579-b07a6f80-b570-11ea-9917-ea27138d0a5a.png">

versus version 0.4.3:

<img width="720" alt="Screen Shot 2020-06-23 at 4 50 29 PM" src="https://user-images.githubusercontent.com/19657652/85474290-adcc4a00-b571-11ea-9acc-10b7ecc43e6e.png">

I checked the relevant HTML code and it's the same for both versions:

```html
<dl class="field-list">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul>
<li><p><strong>array</strong> (<em>2d array-like of int, optional</em>) – Array specifying complex grid of subplots. Think of
this array as a “picture” of your figure. For example, the array...
```

See also [this branch](https://github.com/lukelbd/proplot/tree/docs-test). Btw all `sphinx-automodapi` does is generate `autosummary` directives to catalogue all the public functions/classes/methods.

**Comment by lukelbd** [comment] 2020-06-24 02:00
You should be able to reproduce this by [cloning my branch](https://github.com/lukelbd/proplot/tree/docs-test), creating a conda environment with `docs/environment.yml`, and running `make html` inside the `docs` folder.

**Comment by agjohnson** [comment] 2020-06-24 16:58
Okay, so the second image is correct, the third is a bug in Sphinx 3 + sphinx_rtd_theme == 0.4.3. If you use `html4_writer = True` with sphinx_rtd_theme 0.4.3, you should get something close to the second image. I've suggested something like the third image for an improvement to the listing, but for now, 0.5.0 approximates what 0.4.3 + html4 writer.

The first image is definitely a bug of sorts. The nested table is ultimately the cause here, though it shouldn't cause the entire display to expand like you're seeing. I should be able to add a test case that easily reproduced this -- and wide block content will end up triggering this sort of display.

I'd be curious what the behavior of sphinx_rtd_theme 0.4.3 + `html4_writer = True` is. My guess is it's something close to, but not as heinous as the first image.

**Comment by lukelbd** [comment] 2020-06-24 18:59
Sorry which images are you referring to by "first/second/third"?

My last post has 4 images -- the first 2 show sphinx_rtd_theme 0.5.0 with a margin bleed, the third image shows sphinx_rtd_theme 0.5.0 without a margin bleed but still with the same weird style (separate columns for the `Parameters:` title and bullet points, rather than normal section headers), and the fourth image shows sphinx_rtd_theme 0.4.3 with the "correct" style (normal section headers).

**Comment by lukelbd** [comment] 2020-06-24 20:37
Yep I still get the table-induced margin bleed with `html4_writer = True` in `conf.py` and sphinx_rtd_theme 0.4.3. You're right that it's not quite as heinous :)

<img width="861" alt="Screen Shot 2020-06-24 at 2 36 16 PM" src="https://user-images.githubusercontent.com/19657652/85625052-137b0d80-b628-11ea-938a-65b4df8fa5ae.png">

**Comment by Blendify** [comment] 2021-03-12 20:58
I am closing this as resolved, the current style is intended and it seems the original bug is fixed. OP's examples also no longer show the issue.

**Closed by Blendify** 2021-03-12 20:58 UTC
Labels: Accepted, Bug
