### ISSUE TITLE
No padding in C++ declarations

### ISSUE THREAD

**Issue by jjimenezshaw** [readthedocs/sphinx_rtd_theme#1102] opened 2021-03-28 11:37 UTC
### Problem

C++ declarations do not have padding around many terms. That makes reading extremely difficult.
For instance `const MyTypeFoo(const MyTypebar)` where I would expect `const MyType Foo (const MyType bar)`

### Reproducible Project
Directly in documentation:
https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/api.html#c-api

- `const MyTypeFoo(const MyTypebar)` vs `const MyType Foo (const MyType bar)`
- `template<typenameT,std::size_tN>` vs `template <typename T, std::size_t N>`
- `floatSphinx::version` vs `float Sphinx::version`
- `intversion` vs `int version`
- `typedef std::vector<int>List` vs `typedef std::vector<int> List`
- `protected enum struct MyScopedVisibilityEnum:std::underlying_type<MySpecificEnum>::type` vs 
`protected enum struct MyScopedVisibilityEnum : std::underlying_type<MySpecificEnum>::type`

![image](https://user-images.githubusercontent.com/15678366/112750726-8a37a380-8fca-11eb-959e-d0a9b6e5903b.png)

#### Expected Results

See `Reproducible Project` section

### Environment Info
Any?
Detected with 
- Python Version: 3.8.5
- Sphinx Version: 2.0.1
- RTD Theme Version: 0.4.3

But also detected in RTD documentation.

**Comment by Blendify** [comment] 2021-03-28 17:32
This is a duplicate of #694

**Closed by Blendify** 2021-03-28 17:32 UTC
Labels: Bug, Needed: replication
