### ISSUE TITLE
Feature: Mobile Optimized Codebocks + Language Interpretation

### ISSUE THREAD

**Issue by Mentors4EDU** [readthedocs/sphinx_rtd_theme#1045] opened 2021-02-08 03:04 UTC
### Problem
Code blocks don't resize or aren't dynamic in mobile responsive views

### Reproducible Project

Pytorch's Sphinx theme is able to have responsive codeblocks, but unsure how to integrate this to the regular rtd theme

### Other
Sphinx has some language interpretation, but XML, YAML, Java, Puppet, etc. don't seem to render as well in the codeblock
`` .. code:: LANG`` arguments

*This is a feature request I want to subscribe to, not a bug*

**Comment by stsewd** [comment] 2021-02-08 16:01
> Sphinx has some language interpretation, but XML, YAML, Java, Puppet, etc. don't seem to render as well in the codeblock

Do you have some examples? I think that's mostly to do with pygmets (the lib is used to parse/lex different languages in code blocks)

**Comment by Blendify** [comment] 2021-02-08 20:52
> > Sphinx has some language interpretation, but XML, YAML, Java, Puppet, etc. don't seem to render as well in the codeblock
> 
> Do you have some examples? I think that's mostly to do with pygmets (the lib is used to parse/lex different languages in code blocks)

Correct, changes to add or improve different languages should be handled in https://pygments.org/ and sphinx.

**Comment by Mentors4EDU** [comment] 2021-02-08 20:57
It is strange though, because pygments supports many of these languages, but unsure why they are rendering in GitHub but not in the readthedocs. Is it a problem tied to sphinx or this theme? Though, I would be interested in the other issue I have more w/ codeblocks which is resizing. Both of them could be an improvement one way or the other

**Comment by stsewd** [comment] 2021-02-09 18:11
> It is strange though, because pygments supports many of these languages, but unsure why they are rendering in GitHub but not in the readthedocs. Is it a problem tied to sphinx or this theme? 

That would be a sphinx problem, yes.

Also, for the original problem, do you mean that code blocks should wrap long lines instead of adding an scroll bar?

![Screenshot_2021-02-09 Configuration File V2 — Read the Docs 5 8 5 documentation](https://user-images.githubusercontent.com/4975310/107407305-81047d00-6ad7-11eb-8d86-e31f866c6289.png)

![Screenshot_2021-02-09 Extending PyTorch — PyTorch 1 7 1 documentation(1)](https://user-images.githubusercontent.com/4975310/107407396-9bd6f180-6ad7-11eb-9921-64613fff0f9d.png)

Personally I don't like wrapping, and I'm not sure if that's required for mobile, maybe an option? this can also be done by adding a custom css rule I guess.

The change is https://github.com/readthedocs/sphinx_rtd_theme/blob/5d0a396bf99125b5bfc1ae46aeab9af8dda8feb6/src/sass/_theme_rst.sass#L83-L83

to wrap lines that can be changed to `pre-wrap`

**Comment by Mentors4EDU** [comment] 2021-02-10 01:19
No I am saying let us say I want a single line like
``curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh`` that line cuts off on mobile because it is too many characters rather then wrapping. For large code blocks, it isn't as much as a problem. Resizing for long lines of code or some sort of optimization in regards to long lines of code would be nice.

**Comment by stsewd** [comment] 2021-02-10 01:55
@Mentors4EDU I think you mean https://github.com/readthedocs/sphinx_rtd_theme/issues/321?

**Comment by Blendify** [comment] 2021-02-11 21:06
> It is strange though, because pygments supports many of these languages, but unsure why they are rendering in GitHub but not in the readthedocs. Is it a problem tied to sphinx or this theme? Though, I would be interested in the other issue I have more w/ codeblocks which is resizing. Both of them could be an improvement one way or the other

Sphinx uses a very old version of pygments, I am sending a PR to update to a newer version which adds many new languages.

**Comment by Blendify** [comment] 2021-03-12 15:02
Closing as a duplicate of #321, if you find this is a separate issue please reopen this report.

**Closed by Blendify** 2021-03-12 15:02 UTC
Labels: Needed: more information
