### ISSUE TITLE
Bad bullet spacing

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx_rtd_theme#969] opened 2020-06-30 14:46 UTC
Previous to 0.5.0, bullet spacing used to look like 
![image](https://user-images.githubusercontent.com/10674555/86140349-c3d09200-babe-11ea-90e0-052046b253f4.png)

now it looks like
![image](https://user-images.githubusercontent.com/10674555/86140328-bddab100-babe-11ea-8b6c-22c6de43800e.png)

where the spacing is awkward and distracting.

Using Sphinx 3.1.1
Using sphinx_rtd_theme 0.5.0

Source code here: https://github.com/wpilibsuite/frc-docs.
Stable (0.4.3): https://docs.wpilib.org/en/stable
Latest (0.5.0): https://docs.wpilib.org/en/latest

**Comment by Daltz333** [comment] 2020-07-10 02:25
Doing some further investigation it seems like the ``$base-line-height`` variable may be invalid

**Comment by Daltz333** [comment] 2020-07-18 03:55
This problem still exists in Sphinx 3.1.2

**Comment by jack1142** [comment] 2020-08-19 21:58
Related issue: #943 

And comment that might help someone with making PR for this:
https://github.com/readthedocs/sphinx_rtd_theme/issues/943#issuecomment-645680097

**Comment by Blendify** [comment] 2021-03-11 21:06
Closing, this is a duplicate of #943

**Closed by Blendify** 2021-03-11 21:06 UTC
Labels: Improvement
