### ISSUE TITLE
Make the documentation pages easy to read in narrow-window browsers

### ISSUE THREAD

**Issue by 10110111** [readthedocs/sphinx_rtd_theme#858] opened 2019-11-16 21:03 UTC
## Details
I'm surfing the web from a window with size 1000x850 px, and when I open some documentation powered by ReadTheDocs, it's quite hard to actually read the useful content due to the table of content taking a large chunk of the screen width — until you expand the window, which takes away screen space (not everyone has a high-res monitor yet). See the screenshot below.

I have to use an ad blocker to remove the TOC, which is a poor solution: in case I do need it, I'll have to go through the ad blocker settings to remove this rule.

![Screenshot - 161119 - 23:47:10](https://user-images.githubusercontent.com/6376882/68999043-a0f4c300-08cb-11ea-969c-1790ce84090c.png)

* Read the Docs project URL: https://picamera.readthedocs.io/en/latest/recipes2.html
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

I suggest that the TOC have a button to collapse it to the side, like e.g. Google Maps have:

![Screenshot - 161119 - 23:49:59](https://user-images.githubusercontent.com/6376882/68999054-ec0ed600-08cb-11ea-85e0-53f466351fda.png)

which on click becomes:

![Screenshot - 161119 - 23:51:08](https://user-images.githubusercontent.com/6376882/68999077-3e4ff700-08cc-11ea-9ad8-d1b7b9338a5b.png)

## Actual Result

What actually happens is that the TOC just takes all the space without any easy way to collapse it.

**Comment by stsewd** [comment] 2019-11-18 15:33
Thanks for the report, I'm transferring this issue to our theme repo.

**Comment by agjohnson** [comment] 2019-11-18 20:09
We already have this feature, docs should scale based on viewport size:

![image](https://user-images.githubusercontent.com/1140183/69085727-5d9d7000-0a03-11ea-83d6-8e4c7e97c57f.png)

It sounds like your browser isn't narrow enough to trigger this view, the breakpoint is at 768px.

There is already an issue here for this, #336, but attempts at a PR for this didn't address how to keep the navigation locked to collapsed as the reader navigates between pages.

Closing this as a duplicate.

**Closed by agjohnson** 2019-11-18 20:09 UTC

**Comment by flywire** [comment] 2020-02-19 21:37
**Please reopen this issue.** This issue was identified as a duplicate of #336 which was a poor fit and closed.

Need to be able to define max-width required to display TOC which will vary by content.

Where screen is not wide enough to display TOC and content a poor [workaround](https://github.com/LibreCAD/docs/pull/68/commits/2866a6b5363122ce06a929665d195c2af223ff2a) is defining `@media screen and (max-width: NEWpx)` the same as `@media screen and (max-width: 768px)`. Further [discussion](https://github.com/LibreCAD/docs/pull/68).

**Comment by ruffsl** [comment] 2020-04-28 18:48
> It sounds like your browser isn't narrow enough to trigger this view, the breakpoint is at 768px.

I believe relying on hardcoded magic numbers for view triggers does not serve general accessibility.
