### ISSUE TITLE
Nested objects can display side by side

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#294] opened 2016-05-02 08:16 UTC
If nested elements in a class/etc have short content, and two end up in order, they will appear side by side.

Need to test the following fix:

```
.rst-content dl:not(.docutils) dl.property {
    width: 100%;
}
```

refs rtfd/sphinx-autoapi#33

**Comment by Blendify** [comment] 2017-03-09 23:34
Mind pointing to an example of this?

**Comment by Blendify** [comment] 2021-03-13 06:58
I don't think this can happen anymore, I have never seen this happen in the past 4 years. Closing because this is not reproducible.

**Closed by Blendify** 2021-03-13 06:58 UTC
Labels: Needed: more information, Needed: patch, Needed: tests
