### ISSUE TITLE
Enhance documentation with info about html_context

### ISSUE THREAD

**Issue by langner** [readthedocs/sphinx_rtd_theme#156] opened 2014-10-17 17:44 UTC
Recently wanted to investigate the details about html_context for cclib/cclib.github.io#8 and could not find anything. It would be nice to have something in the docs.

**Comment by Blendify** [comment] 2017-03-11 22:28
This is a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/231

**Comment by jessetan** [comment] 2017-12-27 11:02
This does not seem to be fully covered by #231. Only `:github_url:`, `:bitbucket_url:`, and `:gitlab_url:` are documented, no other options are, nor where to put them. Reopening.

**Comment by htgoebel** [comment] 2018-06-22 21:48
Hmm, this was closed as duplicate, then reopend since it is not. Still the label "duplicate" is still present. Shouldn't this be removed?

**Comment by peterjc** [comment] 2019-08-14 14:38
Note ``html_context`` can be used with the GitHub, Bitbucket etc links - see example here:

https://github.com/readthedocs/sphinx_rtd_theme/issues/465#issuecomment-521272830

**Comment by stsewd** [comment] 2020-10-08 22:10
Closing in favor of https://github.com/readthedocs/sphinx_rtd_theme/issues/582

**Closed by stsewd** 2020-10-08 22:10 UTC
