### ISSUE TITLE
C++ API, lack of a space between return type and function name

### ISSUE THREAD

**Issue by rynnwu** [readthedocs/sphinx_rtd_theme#1065] opened 2021-02-28 05:39 UTC
### Problem

Formatting C++ API, it should have a space between return type and function name. Like:
```
float Sphinx::version
     ^
     |-- A space here
```
And it was ok in [v0.5.1](https://sphinx-rtd-theme.readthedocs.io/en/0.5.1/demo/api.html#_CPPv4N6Sphinx7versionE)

### Reproducible Project
Occurred in [the latest version](https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/api.html#_CPPv4N6Sphinx7versionE).

### Environment Info

- Python Version: n/a
- Sphinx Version: n/a
- RTD Theme Version: latest

**Comment by StrikerRUS** [comment] 2021-03-01 13:24
I can confirm this also happens in our docs.
https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterCalcNumPredict

In addition, I'm not sure whether it is the same issue or another bug, but with `sphinx_rtd_theme + Breathe` there is no space between argument type and its name in C API. But I remember it happened for rtd version < `0.5.0` as well.


![image](https://user-images.githubusercontent.com/25141164/109502713-660ba400-7aaa-11eb-8418-1cd1f6045fe0.png)

**Comment by stsewd** [comment] 2021-03-01 14:53
Thanks for reporting, this is a duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/694

**Closed by stsewd** 2021-03-01 14:53 UTC
Labels: Bug, Needed: patch
