### ISSUE TITLE
 doxygen content exceding theme width

### ISSUE THREAD

**Issue by SuryaGrandhi** [readthedocs/sphinx_rtd_theme#731] opened 2019-02-27 07:16 UTC
### Problem

I am using doxygen to get API content using rtd theme. What I actually need is:
[Expected output](https://imgur.com/LEB3jcH)

But the content is going out of the width and not able to view the content. Like in here:
[Actual Output](https://imgur.com/CqcIWzC)

### Reproducible Project
The rst file is something like this.

```rst
Functions
=========

Level 1 BLAS
-------------

rocblas_<type>scal()
^^^^^^^^^^^^^^^^^^
.. doxygenfunction:: rocblas_dscal

.. doxygenfunction:: rocblas_sscal
rocblas_<type>copy()
^^^^^^^^^^^^^^^^^^
.. doxygenfunction:: rocblas_dcopy

.. doxygenfunction:: rocblas_scopy
```
#### Procedures Followed

I have tried:
Giving custom css in the **_static** folder.
Adding **css to the class** of the doxygen content.
Tried adding 'body_max_width': '80%' to the **html_theme_options** in conf.py file.

But not able to get any result as expected.

#### Expected Results

So, we need the doxygen API content aligned to the width of the theme but not exceeding the width and overflowing.

### Environment Info

- Python Version:  2.7.6
- Sphinx Version:  2.0.4
- RTD Theme Version:

**Comment by SuryaGrandhi** [comment] 2019-03-01 11:49
@Blendify  Can you help us out here.

**Comment by Blendify** [comment] 2019-03-01 19:27
Is this the website?: https://rocblas.readthedocs.io/en/latest/allapi.html

I don't see the issue here. Also the the expected and actual links in the description are the same.

**Comment by SuryaGrandhi** [comment] 2019-03-02 18:46
> Is this the website?: https://rocblas.readthedocs.io/en/latest/allapi.html
> 
> I don't see the issue here. Also the the expected and actual links in the description are the same.

I have updated the expected output link. The content is going out of the theme width/it is displaying in a single line rather in multiple lines.

**Comment by Blendify** [comment] 2019-03-04 01:48
I can confirm the issue after some digging. This happens when the methods contain long singular "words" opening a PR that should fix this.

**Comment by agjohnson** [comment] 2019-07-18 00:29
@SuryaGrandhi do you have an actual link to the docs you're having trouble with. I don't think we can troubleshoot much with just the linked images.

I see something similar happening here:
![image](https://user-images.githubusercontent.com/1140183/61420537-37828a80-a8c0-11e9-8fcc-c6368c81df37.png)

But your linked examples have spaces in the text that should break. It makes me think your viewport size is altered or is extended due to some long content -- these elements are just filling the extra width.

The PR attached I don't think addresses the issue of a long word, i get this applying the fix on the linked docs above:
![image](https://user-images.githubusercontent.com/1140183/61420660-bd063a80-a8c0-11e9-8509-3baf5ecd5598.png)

But this is because the element is code that is set to `nowrap`.

**Comment by stsewd** [comment] 2020-10-08 20:17
Closing this as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/321

**Closed by stsewd** 2020-10-08 20:17 UTC
Labels: Bug, Needed: more information
