### ISSUE TITLE
Not all fonts included if installed with method "Via Git or Download"

### ISSUE THREAD

**Issue by gertvdijk** [readthedocs/sphinx_rtd_theme#712] opened 2019-01-09 15:30 UTC
### Problem

Not all fonts are provided when using theme from Git (or plain sources), compared to the PyPI released sources.

* FontAwesome is included
* Font Lato is missing
* Font RobotoSlab is missing

The difference in the [PyPI release file](https://files.pythonhosted.org/packages/db/37/f57c7a99827aa03fa8efc24037ff9990deb1c6a7bb2f23c388bd36b8748a/sphinx_rtd_theme-0.4.2.tar.gz) and the [generated sources in Git](https://github.com/rtfd/sphinx_rtd_theme/tree/0.4.2/sphinx_rtd_theme) is that not all fonts are included in the latter.

This seems to be caused by commit 69fafa2e0a05792c239933b38587ced540b1ae1f (since 0.4.0) where several font files are removed (not all, though).

### Reproducible Project

1. Follow installation instructions "Via Git or Download" documentation as per https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html#via-git-or-download.
1. Build your project using `sphinx-build`.
1. Open rendered `index.html` in browser.
1. Find that fonts are not found and thus the browser falls back onto Helvetica etc.

Confirmed that with 0.3.1. release the fonts are included and everything works OK.

#### Error Logs/Results

Browser shows HTTP/404 on font files when deployed.

#### Expected Results

Local development from Git sources should be working fine with the documented approach.

### Environment Info

- Python Version: 2.7.15rc1 (Ubuntu 18.04)
- Sphinx Version: 1.8.3
- RTD Theme Version: 0.4.2

**Comment by justb4** [comment] 2019-03-04 18:07
Confirmed, also fonts missing when using a the latest Release .zip download like [0.4.3](https://github.com/rtfd/sphinx_rtd_theme/releases/tag/0.4.3). Strangely enough when installing 0.4.3 via Pip (Python 2.7) the fonts *are* present. But they add quite some MB (about 8-9 MB) to rendered docs, so thought they might have been removed for something more clever like remote load in browser on demand. But I would not mind a fall-back to any other non-serif fonts.

**Comment by justb4** [comment] 2019-03-04 21:10
IMHO Looks like the problem is that the `Roboto` and `Lato` fonts *are* present in the repo but within top dir: https://github.com/rtfd/sphinx_rtd_theme/tree/master/fonts. When building for `PyPi` these are copied during the build (Grunt? like on [this line](https://github.com/rtfd/sphinx_rtd_theme/blob/master/Gruntfile.js#L38) to the target dir under `static/fonts`. So when using `sphinx_rtd_theme` subdir directly from GitHub (and possibly a Release)  these font dirs are missing. 

To fix for local, you can hand-copy the `Lato` and `Roboto` dirs to `sphinx_rtd_theme/static/fonts`.

**Comment by gertvdijk** [comment] 2019-03-05 08:39
Yeah, when I did some more research, the only thing I can imagine is that this hand-copying is now part of a manual release process, breaking the usage straight from source.

**Comment by jessetan** [comment] 2019-03-07 10:21
The fonts are not in static/fonts by default because the idea was to move away from supporting installing master and releasing more often https://github.com/rtfd/sphinx_rtd_theme/issues/379#issuecomment-353793455. Keeping theme.js and theme.css updated in master is an extra step on every merged PR and requires resolving all conflicts.

The same applies for Font Awesome, which is a bower dependency and not present if you clone the repo.
We could mitigate missing Roboto and Lato by putting some symlinks in the repo

**Comment by agjohnson** [comment] 2020-05-06 21:43
The upcoming 0.5.0rc1 release going out shortly will temporarily solve issues like this, however we will be moving away from storing built artifacts in the repository in future releases. We no longer recommend this installation method in our docs.

We'll have a deprecation path for users, but you should be updating your installation path to PyPI soon.

**Closed** 2020-05-06 21:52 UTC
