### ISSUE TITLE
Breadcrumbs and navigation menu not working properly

### ISSUE THREAD

**Issue by prayer007** [readthedocs/sphinx_rtd_theme#1172] opened 2021-06-25 11:56 UTC
### Problem

I am using the sphinx_rtd_theme with autosummary extension for generating the docs automatically. But for now the menu navigation nor the breadcrumbs is not working properly. The menu is always closing if I click a menu item. Also some submenu items are not shown. Lets assume I have 3 main classes A, B, C with some methods A.m1, A.m2... If I click on A.m1 the breadcrumbs should show A >> A.m1. But this is not working. The breadcrumbs only shows A.m1. I dont know if thats a missconfiguration or a bug. It looks like there is a wrong or not existing linking/routing for the rst files. I want the menu and breadcrumbs to work like in this example: https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.location.Location.html  

### Reproducible Project

https://vps2106233.servdiscount-customer.com/sphinx/ 

#### conf.py
```rst
html_theme = 'sphinx_rtd_theme'
master_doc = 'index'
html_static_path = ['_static']
source_suffix = '.rst'
pygments_style = 'sphinx'
autosummary_generate = True
napoleon_use_rtype = False  # group rtype on same line together with return
make_github_url = "https://lifv002.joanneum.at/stn/mpc_tagger_areal/blob/master"
html_css_files = ["custom.css"]
html_show_sphinx = False
html_logo = "_static/jr_logo.png"

```
### Environment Info

- Python Version: 3.8.5 
- Sphinx Version: 4.0.2
- RTD Theme Version: 0.5.2

**Comment by prayer007** [comment] 2021-06-28 10:18
The issue was caused by a wrong syntax in the .rst file.

WRONG: 
.. autosummary::
  
    :toctree: autogen/
   
   data.ForecastData
   data.HistoryData 
   
RIGHT:

.. autosummary::
   :toctree: autogen/
   
   data.ForecastData
   data.HistoryData

**Comment by stsewd** [comment] 2021-06-28 14:51
Looks like the syntax error was the cause, can we close this issue?

**Closed** 2021-08-06 19:06 UTC
Labels: Bug, Needed: replication
