### ISSUE TITLE
Enumerated lists with mixed numbering broken

### ISSUE THREAD

**Issue by jantman** [readthedocs/sphinx_rtd_theme#718] opened 2019-01-30 12:48 UTC
### Problem

Using 0.4.2, nested enumerated lists in HTML output use the same number or letter as the parent list instead of using the defined or default nested list numbering.

I believe this is likely related to #484, but has nothing to do with bullet (non-enumerated) lists.

### Reproducible Project

```rst
A. Foo

   1) Blam
   #) Blarg

      i. Something

   #) Quux

#. Bar
#. Baz
```

#### Error Logs/Results

The result with ``html_theme = "sphinx_rtd_theme"`` is incorrect numbering. The visible output in a browser is:

![rtd](https://user-images.githubusercontent.com/273454/51982050-ee9a5f00-2462-11e9-83e1-ed53c2b3abf3.png)

#### Expected Results

The expected result can be achieved using the alabaster theme (``html_theme = 'alabaster'``):

![alabaster](https://user-images.githubusercontent.com/273454/51982052-f1954f80-2462-11e9-9a37-2892217bfe03.png)

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 1.8.3
- RTD Theme Version: 0.4.2

**Comment by jantman** [comment] 2019-01-30 16:42
For this particular (exact) example, I was able to fix the issue with the following theme CSS override:

```css
.rst-content ol.arabic > li { list-style-type: decimal !important }
.rst-content ol > li > ol { margin-bottom:0 !important }
.rst-content ol.lowerroman > li { list-style-type: lower-roman !important }
```

**Comment by andrensairr** [comment] 2020-03-30 01:22
This is apparent in the [documentation](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html), showing nested ordered lists with different numbering which is not in fact different:

![image](https://user-images.githubusercontent.com/13380307/77866748-04cac780-7280-11ea-8a6e-6fabffaa7144.png)

My experience is that nested unordered lists are also affected; as one would expect from the culprit CSS rule:

```
.rst-content .section ol.loweralpha, .rst-content .section ol.loweralpha li {
    list-style: lower-alpha;
}
```

**Comment by adam-grant-hendry** [comment] 2020-09-07 18:51
@andrensairr Agreed. The `sphinx-rtd` docs are misleading. Looking at the `raw` source under enumerated lists (section 4.1.1), they do not use nested list numbering syntax. Rather, they hard-code the numbering/lettering.

**Comment by stsewd** [comment] 2020-10-08 21:26
Closing as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/484

**Closed by stsewd** 2020-10-08 21:26 UTC
Labels: Bug
