### ISSUE TITLE
Logo missing whith 'logo_only': True

### ISSUE THREAD

**Issue by virtualritz** [readthedocs/sphinx_rtd_theme#872] opened 2020-01-26 17:53 UTC
### Problem

I have set a `html_logo` in `conf.py`. The logo is shown under the home icon/name in the sidebar, as expected.
However, as soon as I set the `logo_only` option to `True`, the logo disappears from the sidebar.

### Reproducible Project

https://github.com/virtualritz/nsi-docs
https://nsi.readthedocs.io/

### Environment Info

- Python Version: 3.7.6
- Sphinx Version: 2.3.1
- RTD Theme Version: live version

**Comment by mondeja** [comment] 2020-03-21 02:12
Try setting next CSS content in your `theme_overrides.css`:
```css
a img.logo {
  width: 100px;
}
```

**Comment by virtualritz** [comment] 2020-03-25 23:21
Doesn't work for me. Logo is still amiss. But thanks for the suggestion.

**Comment by agjohnson** [comment] 2020-05-03 19:25
We use an SVG logo without issue on our docs. I thin the issue is your SVG, the dimensions are way off:
![image](https://user-images.githubusercontent.com/1140183/80923488-624fa980-8d41-11ea-8931-68e7781814d1.png)

You can also use CSS to resolve this on your docs, but your selector specificity is not high enough to override the default styles.

Closing this as it is not an issue with our theme

**Closed by agjohnson** 2020-05-03 19:25 UTC
