### ISSUE TITLE
Feature request: ability to customize logo link

### ISSUE THREAD

**Issue by simonw** [readthedocs/sphinx_rtd_theme#977] opened 2020-07-12 19:32 UTC
I'd like to be able to customize the URL that is linked to by the project logo at the top of the navigation.

For example, if I was using the theme with a logo like this: https://docs.readthedocs.io/en/stable/index.html - I'd like to be able to customize it so that clicking on the "Read the Docs" logo navigates to https://readthedocs.org/

<img width="1100" alt="Read_the_Docs__Documentation_Simplified_—_Read_the_Docs_5_1_5_documentation" src="https://user-images.githubusercontent.com/9599/87254961-9fb86d80-c43b-11ea-9c56-946a9c3d9f22.png">

**Comment by simonw** [comment] 2020-07-12 19:34
Here's the relevant code: https://github.com/readthedocs/sphinx_rtd_theme/blob/7df2524941ff10e6ca0a080c36217150fb1a9c91/sphinx_rtd_theme/layout.html#L118-L130

I suggest adding a new `html_theme_option` (https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html) called something like `logo_url` - so I could do something like this:

```python
html_theme_options = {
    "logo_url": "https://readthedocs.org/",
    "logo_only": True,
}
```

**Comment by simonw** [comment] 2020-07-12 19:49
The reason I want to do this is that it feels like the easiest way to integrate RTD-hosted documentation with my own custom project website.

**Comment by jobec** [comment] 2020-07-15 08:16
I've also got a use case for this. The documentation is sometimes part of a bigger site. Allowing this link to be customized can bring the reader back to the overview of the entire site, instead of only the top of the documentation.

**Comment by JamesRandom** [comment] 2020-07-15 22:14
I would also like to be able to do this. We have an overview/index document that provides links to all the documents for our products, which are all defined as sub-projects (https://docs.graphcore.ai). We would like the logo link to go back to this "master" document, rather than the contents page of each individual document. (My workaround is to create a template file to add a link to the header of each document.)

**Comment by stsewd** [comment] 2020-10-08 15:42
Closing as duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/777. There we are deciding to use a block instead of another option.

**Closed by stsewd** 2020-10-08 15:42 UTC
Labels: Improvement

**Comment by simonw** [comment] 2020-12-07 19:09
For anyone who's interested, I figured out how to do this with a custom Sphinx template. I wrote up how to do that here: https://til.simonwillison.net/readthedocs/custom-sphinx-templates
