### ISSUE TITLE
Toc collapses back to level 5 of hierarchy.

### ISSUE THREAD

**Issue by yguenduez** [readthedocs/sphinx_rtd_theme#893] opened 2020-04-02 09:20 UTC
First of all, thanks for the great work and effort you put in!

### Problem

With the improved indentation (which is a really cool feature) of #852 I see that the toc collapses back to level 5 of the toc hierarchy. If you click an item below level 5, the toc collapses back to level 5. Because I am a newb with sass and the latter, I cannot (yet) do a PR myself.

### Reproducible Project

Click on a toc item below level 5.

This is the only config I ran with sphinx:
```python
html_theme_options = {
    'collapse_navigation': False, 
    'sticky_navigation': False,
    'navigation_depth' : -1 #endless depth
}
```

#### Error Logs/Results

The toc collapses back to Level 5, if I click an item below level 5.
![toc_collapses_to_lvl5](https://user-images.githubusercontent.com/49899586/78230620-df34fc80-74d1-11ea-9f56-6f0c10db91d7.gif)

#### Expected Results

The toc should stay expanded at the current level the item is.

### Environment Info

- Python Version: 3.6.9
- Sphinx Version: 2.4.4
- RTD Theme Version: current master: commit e8736948d6c6d2da9318d2c8bdc08def18a5ada9

**Comment by yguenduez** [comment] 2020-04-02 13:37
It seems, you just have to expand the hard coded lines [here](https://github.com/readthedocs/sphinx_rtd_theme/blob/master/src/theme.js#L154) and build the statics in the theme with it, if I am not wrong.

**Comment by s-weigand** [comment] 2020-04-11 13:13
@yguenduez Could you check if this issue still persists?
I can't reproduce it on the current HEAD (3503493).
If it does, could you provide a minimal example to reproduce the issue?

**Comment by stsewd** [comment] 2020-10-07 23:21
Closing as inactivity, please link us to a project where you have this problem if still persists

**Comment by s-weigand** [comment] 2020-10-08 16:36
I actually have an example for this, in the [autogenerated API docs](https://pyglotaran.readthedocs.io/en/latest/user_documentation/api/glotaran/builtin/file_formats/sdt/sdt_file_reader/glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt.html#glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt) of a project I contribute to.

And it can be fixed by replacing:
https://github.com/readthedocs/sphinx_rtd_theme/blob/14856443865f869ccb3e88a3d1e7c432d8768dd3/src/theme.js#L147-L156

with:
```js
            $('.wy-menu-vertical .current').removeClass('current');
            link.addClass('current');
            link.closest('li.toctree-l1').parent().addClass('current');
            for (let i = 1; i <= 10; i++) {
                link.closest(`li.toctree-l${i}`).addClass('current');
            }
            link[0].scrollIntoView();
```
I uploaded my [testexample](https://s-weigand.github.io/pyglotaran/user_documentation/api/glotaran/builtin/file_formats/sdt/sdt_file_reader/glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt.html).

I guess [Template Literals are widely enought supported](https://caniuse.com/template-literals) to use them.
If you prefer a style supported by `IE`, it could also be written as:
```js
                link.closest('li.toctree-l' + String(i)).addClass('current');
```
or

```js
                link.closest('li.toctree-l' + i).addClass('current');
```

I think creating a reproducible example is only possible with `autodoc` and a deeply nested project structure, due to the limited amount of heading levels `sphinx` provides us with.

Since I already wrote it for testing purposes, I can make a PR if you want.

**Comment by stsewd** [comment] 2020-10-08 17:08
Thanks for the reproducible project and the solution! I'd left the compatibility thing to @agjohnson to decide.

**Comment by s-weigand** [comment] 2020-10-08 17:16
Using [part](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) as top level element in the [structure demo](https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/structure.html#), we can get down to level6.

**Comment by stsewd** [comment] 2021-02-09 18:43
So, I'm not able to reproduce the behavior that is described in this issue https://s-weigand.github.io/pyglotaran/user_documentation/api/glotaran/builtin/file_formats/sdt/sdt_file_reader/glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt.html

This branch is using the current theme and doesn't replicate that behavior as well https://sphinx-rtd-theme--1039.org.readthedocs.build/en/1039/demo/lists_tables.html#but-deeper-down-the-rabbit-hole (and adding another level doesn't get listed in the toc tree actually)

**Comment by s-weigand** [comment] 2021-02-09 19:05
The reproducible example is the [actual docs hosted at RTD](https://pyglotaran.readthedocs.io/en/latest/user_documentation/api/glotaran/builtin/file_formats/sdt/sdt_file_reader/glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt.html#glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt), the [gh-pages link to my fork](https://s-weigand.github.io/pyglotaran/user_documentation/api/glotaran/builtin/file_formats/sdt/sdt_file_reader/glotaran.builtin.file_formats.sdt.sdt_file_reader.read_sdt.html) used `sphinx_rtd_theme` with my proposed fixes in place (it was only meant to show what I would expect how it should work).

> and adding another level doesn't get listed in the toc tree actually

My guess is that `navigation_depth` is not changed to `-1` or a value of `6+` on that branch (the value on the default branch is `5`).

https://github.com/readthedocs/sphinx_rtd_theme/blob/5d0a396bf99125b5bfc1ae46aeab9af8dda8feb6/docs/conf.py#L62

**Comment by stsewd** [comment] 2021-02-09 23:16
Thanks for the clarification!

**Closed** 2021-03-15 18:51 UTC
Labels: Accepted, Bug
